Skip trivy binary while scanning
aquasecurity/trivy pull request #1001
Opened 2021-05-18 14:50 UTC by rahul2393

[Issue](https://github.com/aquasecurity/trivy/issues/997)

2021-05-18 14:50 UTC, rahul2393 commented
<img width="1440" alt="Screenshot 2021-05-18 at 8 18 51 PM" src="https://user-images.githubusercontent.com/18293335/118673262-7d8b3b00-b816-11eb-982e-5767948fb183.png">

2021-05-18 15:01 UTC, rahul2393 commented
<img width="1440" alt="Screenshot 2021-05-18 at 8 31 03 PM" src="https://user-images.githubusercontent.com/18293335/118675250-11a9d200-b818-11eb-9f21-5c19f3c1cd98.png">

2021-05-19 01:49 UTC, knqyf263 requested changes

2021-05-19 01:49 UTC, knqyf263 commented on go.mod
> +replace golang.org/x/crypto => golang.org/x/crypto v0.0.0-20201216223049-8b5274cf687f
Do not use `replace`, but update dependencies.

2021-05-21 07:47 UTC, knqyf263 reviewed
Did you run `go mod tidy`?

2021-05-21 07:47 UTC, knqyf263 commented on .github/workflows/scan.yaml
> +name: Scan
```suggestion
name: Scan Vulnerabilities
```

2021-05-21 07:48 UTC, knqyf263 commented on .github/workflows/scan.yaml
> +    name: Scan repo
```suggestion
    name: Scan Go vulnerabilities
```

2021-05-23 07:27 UTC, rahul2393 commented
> Did you run `go mod tidy`?

yes

2021-05-23 08:20 UTC, knqyf263 approved these changes

2021-05-23 08:21 UTC, merged

2021-09-09 11:29 UTC, piyush94 commented
What is meant by "add Go scanning" in the PR title? Did Trivy was not capable to scan Go packages/dependencies earlier?

2021-09-11 06:55 UTC, knqyf263 commented
It was added in v0.17.0.
https://github.com/aquasecurity/trivy/discussions/966