fix(oracle): handle advisories contain ksplice versions
aquasecurity/trivy pull request #1209
Opened 2021-09-02 14:48 UTC by afdesk

Improve a handling of advisories contain ksplice versions:
* when one of them doesn't have ksplice, we'll also skip it
* extract kspliceX and compare it with kspliceY in advisories
* if kspliceX and kspliceY are different, we will skip the advisory.

Fixes #1205

2021-09-02 17:13 UTC, knqyf263 requested changes
Looks good! Thanks. I suggested some ideas to simplify code.

2021-09-02 17:13 UTC, knqyf263 commented on pkg/detector/ospkg/oracle/oracle.go
> +
If we can assume ksplice is separated by dot, how about this?

```suggestion
func extractKspliceNumber(v string) string {
	subs := strings.Split(strings.ToLower(v), ".")
	for _, s := range subs {
		if strings.HasPrefix(v, "ksplice") {
			return s
		}
	}
	return ""
}

```

2021-09-02 17:13 UTC, knqyf263 commented on pkg/detector/ospkg/oracle/oracle.go
> +				}
I think we can simplify it.

```suggestion
			if extractKspliceNumber(adv.FixedVersion) != extractKspliceNumber(pkg.Release) {
				continue
			}
```

2021-09-02 17:13 UTC, knqyf263 commented on pkg/detector/ospkg/oracle/oracle_test.go
> +				pkgs: []ftypes.Package{
We already have the same test for ksplice1. These tests are duplicate. We should add only 1 test where the installed version has ksplice2.

2021-09-02 17:13 UTC, knqyf263 commented on pkg/detector/ospkg/oracle/oracle_test.go
> +}
We can test this method through TestScanner_Detect

2021-09-03 06:37 UTC, afdesk commented on pkg/detector/ospkg/oracle/oracle.go
> +				}
sure, your was is better!

2021-09-05 08:29 UTC, knqyf263 approved these changes

2021-09-05 08:29 UTC, merged