Quick guide for using trivy with jenkins
aquasecurity/trivy pull request #1266
Opened 2021-10-01 18:09 UTC by tofuatjava

2021-10-04 16:23 UTC, krol3 reviewed
Please check the spelling in the text, for example inlcuded, plugn

2021-11-23 22:11 UTC, krol3 submitted a review, later dismissed

2021-11-23 22:11 UTC, krol3 commented on docs/advanced/integrations/jenkins.md
> +sh "trivy image -f json -o results.json aquasec/trivy:0.19.2"
sh "trivy image -f json -o results.json nginx:1.18"
It will be more clear in the sample, using a common image

2021-11-23 22:11 UTC, krol3 commented on docs/advanced/integrations/jenkins.md
> +A simple example of a declarative pipeline in a kubernetes envionment:
I couldn't test with successful this pipeline. I tried this and works:

```
timestamps {
	node(){
    stage('install trivy') {
      sh "curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.21.0"
    }
        
    stage('scan with trivy') {
      sh "trivy image -f json -o results.json nginx:1.18"
      recordIssues enabledForFailure: true, failOnError: true, aggregatingResults: true, tool: trivy(pattern: 'results.json')
    }
   }
}
```

2021-11-23 22:16 UTC, krol3 commented on docs/advanced/integrations/jenkins.md
> +A simple example of a declarative pipeline in a kubernetes envionment:
@tofuatjava check the results using this sample

<img width="1767" alt="Screen Shot 2021-11-23 at 19 15 49" src="https://user-images.githubusercontent.com/8355621/143137761-46e60cb4-4b14-4ad7-85b8-d1ef6e0eabe0.png">

2021-12-07 18:21 UTC, tofuatjava reviewed
changing to nginx image is fair enough :-)

Nevertheless, I want to vote for my declarative pipeline, because it is more common and cleaner to read.

2021-12-07 18:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/trivy?pullRequest=1266) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/trivy?pullRequest=1266) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: tofuatjava<br/>:x: tom<br/><hr/>**tom** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/trivy?pullRequest=1266) it.</sub>

2021-12-14 01:23 UTC, krol3 commented
@tofuatjava  we have another user in the commit, could you review the license/CLA?

2021-12-16 18:26 UTC, tofuatjava commented
> 

this was actually myself from a different pc. sorry for that. I do not have a github account with this user. I tried to correct the commiter...

2021-12-28 10:28 UTC, josemaia commented on docs/advanced/integrations/jenkins.md
> +With Jenkins it is possible to do scriped pipelines but also declarative pipelines. I prefere declarative pipelines. You will find more information about pipelines in jenkins at https://www.jenkins.i
```suggestion
With Jenkins it is possible to do scripted pipelines but also declarative pipelines. I prefere declarative pipelines. You will find more information about pipelines in jenkins at https://www.jenkins.io/doc/book/pipeline/.
```

2021-12-29 14:12 UTC, krol3 commented
> > 
> 
> this was actually myself from a different pc. sorry for that. I do not have a github account with this user. I tried to correct the commiter...

@tofuatjava  could you try to resolve this CLA to merge this PR. If you can't. Maybe I could open another PR with your code. I hope your answer. Thanks

2022-02-07 12:46 UTC, krol3 approved these changes
LGTM

2022-02-07 17:56 UTC, knqyf263 requested changes
Could you update mkdocs.yml as well?

2022-09-07 00:22 UTC, krol3 commented
@knqyf263  what do you think of merge this PR, I could create the mkdocs update in another PR.

2022-12-20 16:00 UTC, m4t22 commented
is that working for you? I've tested it with:
- trivy: `v0.35.0`
- warnings-ng: `9.5.0`

And despite the fact that my json is not empty I am getting:
```
[Aquasec Trivy] -> found 0 issues (skipped 0 duplicates)
```

2023-01-03 13:19 UTC, knqyf263 commented
We don't have the resources to maintain that, but we welcome adding community tutorials here. Thanks.
https://aquasecurity.github.io/trivy/v0.36/tutorials/additional-resources/community/

2023-01-03 13:19 UTC, closed without merging