docs : better ouput with the same conformity
aquasecurity/trivy pull request #1474
Opened 2021-12-13 17:04 UTC by Davidffry

2021-12-13 17:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/trivy?pullRequest=1474) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/trivy?pullRequest=1474) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/trivy?pullRequest=1474) it.</sub>

2021-12-13 17:07 UTC, Davidffry commented
Hello, a validation of the documentation,
Same convention is better to read the documention of installation.
but the end of the line for this, don't know.
=== "pikaur"

``` bash
pikaur -Sy trivy-bin
```

=== "yay"

``` bash
yay -Sy trivy-bin
```

## Homebrew

You can use homebrew on macOS and Linux.

```bash
brew install aquasecurity/trivy/trivy
```

2021-12-16 08:05 UTC, knqyf263 requested changes
Thanks for the contribution. Our doc allows copying commands to the clipboard with one click. I think the leading `$` is bothering in such cases. But missing `$` is confusing in the case of multiple lines. So, we removed the leading `$` only when the command is one line. Any idea?

2021-12-20 08:47 UTC, Davidffry commented on docs/getting-started/installation.md
> +``` bash
@knqyf263 please find my solution for : `only when the command is one line. Any idea?`

```bash
sudo tee /etc/yum.repos.d/trivy.repo << EOF
    [trivy]
    name=Trivy repository
    baseurl=https://aquasecurity.github.io/trivy-repo/rpm/releases/$releasever/$basearch/
    gpgcheck=0
    enabled=1
EOF
```

2021-12-20 16:04 UTC, knqyf263 commented on docs/getting-started/installation.md
> +``` bash
>Please don't remove these indents. They are necessary for content tabs.

Could you see my comments?

2022-04-14 00:05 UTC, closed without merging