docs: add PR template
aquasecurity/trivy pull request #1602
Opened 2022-01-18 13:11 UTC by DmitriyLewen

## Description
Add PR template

2022-01-19 12:03 UTC, AndreyLevchenko requested changes

2022-01-19 12:04 UTC, AndreyLevchenko commented on .github/pull_request_template.md
> +- [ ] I've included a "before" and "after" example (if the PR is a user interface change).
@knqyf263  should we ask about adding motivation of changes to description?

2022-01-23 06:59 UTC, knqyf263 commented on .github/pull_request_template.md
> +- [ ] I've included a "before" and "after" example (if the PR is a user interface change).
We have a section linking to an issue. I believe the issue describes the motivation.

2022-01-23 08:35 UTC, knqyf263 approved these changes

2022-01-23 08:36 UTC, merged