feat(helm): Parameterise ServiceAccount annotations
aquasecurity/trivy pull request #1677
Opened 2022-02-05 07:02 UTC by dowlingw

## Description
Allow customisation of ServiceAccount annotations in helm chart.

## Related issues
- Close #1676

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've followed the [conventions](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2022-02-05 07:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/trivy?pullRequest=1677) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/trivy?pullRequest=1677) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/trivy?pullRequest=1677) it.</sub>

2022-02-05 08:00 UTC, knqyf263 commented
@krol3 Can you take a look?

2022-02-05 08:15 UTC, dowlingw commented
I'll have a look at this build failure now, apologies for that.

2022-02-07 08:58 UTC, dowlingw commented
Hi @knqyf263 [knqyf263](https://github.com/knqyf263), I've fixed the above build error if you're able to re-approve the CI run. Sorry for that! :)

2022-02-07 13:34 UTC, dowlingw commented
Rebased off main following merge of #1681 - this should address the build failure due to `containerd` vulnerability.

2022-02-07 17:49 UTC, krol3 requested changes
Please add a sample of using this new fields in the values.yaml.

Similar to https://github.com/aquasecurity/trivy/blob/main/helm/trivy/values.yaml#L120

2022-02-08 00:44 UTC, dowlingw commented
I wasn't able to think of a good vendor-neutral example, so I've used my specific use case - please let me know if this is a problem and I can try and come up with something different.

2022-02-13 07:48 UTC, merged