Patch go libs
aquasecurity/trivy pull request #1681
Opened 2022-02-05 19:23 UTC by tspearconquest

Signed-off-by: Thomas Spear <tspear@conquestcyber.com>

## Description

## Related issues
- Close #1680

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've followed the [conventions](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2022-02-07 11:50 UTC, knqyf263 requested changes
Thanks for the contribution! Can you apply `go mod tidy`?

2022-02-07 11:52 UTC, knqyf263 commented
I did it. Never mind.

2022-02-07 12:12 UTC, knqyf263 approved these changes

2022-02-07 12:12 UTC, merged

2022-02-14 13:46 UTC, cebidhem commented
Hi, when do you think this could be released ? It's blocking our CI since Trivy detects this vulnerability. Any chance to get it in a patch version ?