chore(ci): auto generation of configs for deb packages
aquasecurity/trivy pull request #1775
Opened 2022-02-27 20:01 UTC by afdesk

## Description
Added auto generation `conf/distributions` for building deb packages.

## Related issues
- Close #1692 

## Checklist
- [ ] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've followed the [conventions](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2022-03-01 12:07 UTC, knqyf263 requested changes
I want you to make sure my suggested changes don't cause any issues.

2022-03-01 12:07 UTC, knqyf263 commented on ci/deploy-deb.sh
> +  echo "Origin: knqyf263.github.io/trivy-repo/deb
We forgot to replace with aquasecurity.

```suggestion
  echo "Origin: aquasecurity.github.io/trivy-repo/deb
```

2022-03-01 12:07 UTC, knqyf263 commented on ci/deploy-deb.sh
> +Label: github.io/knqyf263
```suggestion
Label: github.io/aquasecurity
```

2022-03-03 18:24 UTC, afdesk commented
> I want you to make sure my suggested changes don't cause any issues.

do you mean changes `knqyf263` to `aquasecurity`?

2022-03-04 11:25 UTC, afdesk commented on ci/deploy-deb.sh
> +  echo "Origin: knqyf263.github.io/trivy-repo/deb
updated

2022-03-04 11:25 UTC, afdesk commented on ci/deploy-deb.sh
> +Label: github.io/knqyf263
ditto

2022-03-04 12:02 UTC, afdesk commented
it seems these changes affect on metadata only.

2022-06-22 08:35 UTC, knqyf263 reviewed
I have another concern now. Does it drop old release supports? For example, will trusty be removed?
https://github.com/aquasecurity/trivy-repo/blob/86725c045b26843c173607ca7a6b04943fb4d1b7/deb/conf/distributions#L57-L63

2022-06-22 12:44 UTC, knqyf263 commented
I didn't know `trusty` was still supported. I meant we probably should keep old releases reaching EOL as well.

2022-06-23 13:38 UTC, afdesk commented
> I didn't know `trusty` was still supported. I meant we probably should keep old releases reaching EOL as well.

yes, `trusty` is supported now but only with Extended Security Maintenance (ESM).

`ubuntu-distro-info` allows to select lists of `--all` versions, or `--supported`/`--unsupported` versions.

should we use `--all`?

2022-06-24 04:23 UTC, knqyf263 commented
If we remove old versions, those versions will not work suddenly, right? I'm not saying we should keep supporting, but should not remove packages for those versions.

2022-06-24 13:08 UTC, afdesk commented
> If we remove old versions, those versions will not work suddenly, right? I'm not saying we should keep supporting, but should not remove packages for those versions.

oh, it seems i understood your idea.
then we can build configs for all distros and will include debs only for `supported` and `supported-esm`.

2022-06-24 13:21 UTC, closed without merging

2022-06-24 13:22 UTC, afdesk commented
I accidentally broke this PR, will create a new

2022-06-24 13:28 UTC, afdesk commented
created #2404