feat(report): add support for SPDX
aquasecurity/trivy pull request #2059
Opened 2022-04-27 11:15 UTC by ShiraCohen33

## Description
Add SPDX format support

## Related issues
- https://github.com/aquasecurity/trivy/issues/1819

## Checklist
- [X] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [X] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [X] I've added tests that prove my fix is effective or that my feature works.
- [X] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2022-04-27 11:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/trivy?pullRequest=2059) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/trivy?pullRequest=2059) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/trivy?pullRequest=2059) it.</sub>

2022-04-27 17:35 UTC, seabass-labrax requested changes
This looks really great; thanks for taking the time to implement this feature! I've left a small suggestion for this PR.

2022-04-27 17:35 UTC, seabass-labrax commented on pkg/report/spdx/spdx.go
> +	SPDXVersion         = "SPDX-2.1"
```suggestion
	SPDXVersion         = "SPDX-2.2"
```

The latest version of the [SPDX specification](https://spdx.github.io/spdx-spec/) is 2.2 :smiley:

2022-04-28 12:06 UTC, seabass-labrax commented
@ShiraCohen33 thanks for bumping the SPDX specification version! :smiley:

2022-05-01 09:35 UTC, knqyf263 commented on docs/docs/sbom/spdx.md
> +$ cat result.spdx | jq .
Is this JSON?

2022-05-01 10:40 UTC, ShiraCohen33 commented on docs/docs/sbom/spdx.md
> +$ cat result.spdx | jq .
No, it's a mistake

2022-05-02 10:30 UTC, knqyf263 approved these changes

2022-05-02 10:44 UTC, knqyf263 approved these changes

2022-05-02 10:44 UTC, merged