chore(suse): update EOL dates for SUSE SLES 15.3, 15.4 and OpenSUSE 15.4
aquasecurity/trivy pull request #2403
Opened 2022-06-24 12:53 UTC by macedogm

## Description
SUSE SLES 15.4 and OpenSUSE 15.4 were released, so this PR updates its EOL dates and also for SLES 15.3.

## Related issues
- Close https://github.com/aquasecurity/trivy/issues/2402

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

2022-06-24 13:22 UTC, macedogm commented
CCing @dirkmueller

2022-06-24 20:28 UTC, dirkmueller commented on pkg/detector/ospkg/suse/suse.go
> +		"15.4": time.Date(2028, 6, 24, 23, 59, 59, 0, time.UTC),
can you keep / readd the comment `6 months after SLES 15 SP5 release` here?

2022-06-24 20:28 UTC, dirkmueller requested changes
please update the end date for 15.3

2022-06-24 20:28 UTC, dirkmueller commented on pkg/detector/ospkg/suse/suse.go
> +		"15.3": time.Date(2022, 12, 24, 23, 59, 59, 0, time.UTC),
no, its 12, 31. see https://www.suse.com/lifecycle/

![image](https://user-images.githubusercontent.com/1029152/175662585-fc9d12ee-762c-48d2-adbd-0652f8bac3bb.png)

2022-06-26 06:17 UTC, macedogm commented
Fixed.

2022-06-26 17:01 UTC, knqyf263 commented
@macedogm Thanks! Please let me wait for approval from @dirkmueller.

BTW, is there any way to get these EOL dates via API or something like that? We'd like to automate it.

2022-06-27 07:59 UTC, macedogm commented
> BTW, is there any way to get these EOL dates via API or something like that? We'd like to automate it.

I'll defer this question to @dirkmueller.

2022-06-27 20:08 UTC, dirkmueller approved these changes

2022-06-27 20:10 UTC, dirkmueller commented
> BTW, is there any way to get these EOL dates via API or something like that? We'd like to automate it.

I believe we currently don't offer it via a public API. I will check this and file an issue/PR

2022-06-28 03:26 UTC, knqyf263 approved these changes

2022-06-28 03:26 UTC, knqyf263 commented
@dirkmueller Thanks.

2022-06-28 03:26 UTC, merged