fix(k8s): no error logged if trivy can't get docker image in kubernetes mode
aquasecurity/trivy pull request #2521
Opened 2022-07-15 07:18 UTC by dmazhar-cogniance

## Description
Enabling logs for k8s mode and increasing log level for the failed image scans from debug to warning. Should it be even error?
@josedonizetti mentioned that logging was disabled to not mess the output of report. But it looks like logs are printed before the reports, so looks fine for me. Please let me know if I'm missing anything.

### Before
```
❯ ./trivy k8s -n prod --security-checks vuln deployment/<deployment name>
1 / 1 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 2 p/s
```
### After
```
❯ ./trivy k8s -n prod --security-checks vuln deployment/<deployment name>
2022-07-15T10:15:50.115+0300	INFO	Vulnerability scanning is enabled
1 / 1 [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>] 100.00% ? p/s2022-07-15T10:15:50.813+0300	WARN	failed to scan image XXX.dkr.ecr.us-east-1.amazonaws.com/XXXX: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
	* unable to inspect the image (XXX.dkr.ecr.us-east-1.amazonaws.com/XXXX): Error: No such image: XXX.dkr.ecr.us-east-1.amazonaws.com/XXXX
	* unable to initialize Podman client: no podman socket found: stat /run/user/1000/podman/podman.sock: no such file or directory
	* failed to initialize a containerd client: failed to dial "/run/containerd/containerd.sock": connection error: desc = "transport: error while dialing: dial unix /run/containerd/containerd.sock: connect: permission denied"
	* GET https://XXX.dkr.ecr.us-east-1.amazonaws.com/v2/XXXX: unexpected status code 401 Unauthorized: Not Authorized

1 / 1 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 2 p/s
```

## Related issues
- Close #2505

## Checklist
- [ ] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [ ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2022-07-15 07:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/trivy?pullRequest=2521) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/trivy?pullRequest=2521) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/trivy?pullRequest=2521) it.</sub>

2022-07-15 07:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/trivy?pullRequest=2521) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/trivy?pullRequest=2521) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/trivy?pullRequest=2521) it.</sub>

2022-07-15 13:59 UTC, chen-keinan commented
LGTM!

2022-07-15 13:59 UTC, chen-keinan approved these changes

2022-07-15 14:14 UTC, josedonizetti commented
@dmazhar-cogniance When scanning a single resource it doesn't look to bad, but the problem is when you targeting a namespace, the cluster of a set of pods/etc. For example, for minikube cluster with only one pod I see way too many logging instead of directly see the report. That is why I was expecting for disable/enable more granular 

```
josedonizetti@us-wswanson-dr4x trivy % ./trivy k8s --report=summary all
2022-07-15T11:10:39.184-0300	INFO	Need to update DB
2022-07-15T11:10:39.184-0300	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2022-07-15T11:10:39.184-0300	INFO	Downloading DB...
33.06 MiB / 33.06 MiB [-------------------------------------------------------------------------------------------------------------------------] 100.00% 20.62 MiB p/s 1.8s
2022-07-15T11:10:42.340-0300	INFO	Vulnerability scanning is enabled
2022-07-15T11:10:42.340-0300	INFO	Misconfiguration scanning is enabled
2022-07-15T11:10:42.340-0300	INFO	Secret scanning is enabled
2022-07-15T11:10:42.340-0300	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-15T11:10:42.340-0300	INFO	Please see also https://aquasecurity.github.io/trivy/v0.29.2-65-g852ccc0a5/docs/secret/scanning/#recommendation for faster secret detection
1 / 3 [-------------------------------------------------->____________________________________________________________________________________________________] 33.33% ? p/s2022-07-15T11:10:44.201-0300	INFO	Detected OS: ubuntu
2022-07-15T11:10:44.201-0300	INFO	Detecting Ubuntu vulnerabilities...
2022-07-15T11:10:44.203-0300	INFO	Number of language-specific files: 0
2022-07-15T11:10:44.203-0300	INFO	Detected config files: 0
2022-07-15T11:10:44.208-0300	INFO	Vulnerability scanning is enabled
2022-07-15T11:10:44.208-0300	INFO	Misconfiguration scanning is enabled
2022-07-15T11:10:44.208-0300	INFO	Secret scanning is enabled
2022-07-15T11:10:44.208-0300	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-15T11:10:44.208-0300	INFO	Please see also https://aquasecurity.github.io/trivy/v0.29.2-65-g852ccc0a5/docs/secret/scanning/#recommendation for faster secret detection
1 / 3 [-------------------------------------------------->____________________________________________________________________________________________________] 33.33% ? p/s2022-07-15T11:10:44.446-0300	INFO	Number of language-specific files: 0
2022-07-15T11:10:44.446-0300	INFO	Detected config files: 1
2022-07-15T11:10:44.491-0300	INFO	Vulnerability scanning is enabled
2022-07-15T11:10:44.491-0300	INFO	Misconfiguration scanning is enabled
2022-07-15T11:10:44.491-0300	INFO	Secret scanning is enabled
2022-07-15T11:10:44.491-0300	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-15T11:10:44.491-0300	INFO	Please see also https://aquasecurity.github.io/trivy/v0.29.2-65-g852ccc0a5/docs/secret/scanning/#recommendation for faster secret detection
2 / 3 [---------------------------------------------------------------------------------------------------->__________________________________________________] 66.67% ? p/s2022-07-15T11:10:44.689-0300	INFO	Number of language-specific files: 0
2022-07-15T11:10:44.689-0300	INFO	Detected config files: 1
2022-07-15T11:10:44.728-0300	INFO	Vulnerability scanning is enabled
2022-07-15T11:10:44.728-0300	INFO	Misconfiguration scanning is enabled
2022-07-15T11:10:44.728-0300	INFO	Secret scanning is enabled
2022-07-15T11:10:44.728-0300	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-15T11:10:44.728-0300	INFO	Please see also https://aquasecurity.github.io/trivy/v0.29.2-65-g852ccc0a5/docs/secret/scanning/#recommendation for faster secret detection
3 / 3 [----------------------------------------------------------------------------------------------------------------------------------------------------->] 100.00% ? p/s2022-07-15T11:10:44.771-0300	INFO	Number of language-specific files: 0
2022-07-15T11:10:44.771-0300	INFO	Detected config files: 0
3 / 3 [------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 1 p/s

Summary Report for minikube
┌───────────┬────────────────┬─────────────────────┬────────────────────┬───────────────────┐
│ Namespace │    Resource    │   Vulnerabilities   │ Misconfigurations  │      Secrets      │
│           │                ├───┬───┬────┬────┬───┼───┬───┬───┬────┬───┼───┬───┬───┬───┬───┤
│           │                │ C │ H │ M  │ L  │ U │ C │ H │ M │ L  │ U │ C │ H │ M │ L │ U │
├───────────┼────────────────┼───┼───┼────┼────┼───┼───┼───┼───┼────┼───┼───┼───┼───┼───┼───┤
│ default   │ Deployment/app │   │   │ 34 │ 50 │   │   │   │ 2 │ 10 │   │ 1 │   │   │ 1 │   │
└───────────┴────────────────┴───┴───┴────┴────┴───┴───┴───┴───┴────┴───┴───┴───┴───┴───┴───┘
Severities: C=CRITICAL H=HIGH M=MEDIUM L=LOW U=UNKNOWN


Summary Report for minikube
┌───────────┬──────────┬───────────────────┐
│ Namespace │ Resource │  RBAC Assessment  │
│           │          ├───┬───┬───┬───┬───┤
│           │          │ C │ H │ M │ L │ U │
└───────────┴──────────┴───┴───┴───┴───┴───┘
Severities: C=CRITICAL H=HIGH M=MEDIUM L=LOW U=UNKNOWN
```

2022-07-15 14:16 UTC, josedonizetti requested changes
Look my comment above. We need to explore a bit more how to fix this.

2022-07-15 15:42 UTC, dmazhar-cogniance commented
@josedonizetti , got it. Thanks for pointing this out. What do you think of [this](https://github.com/aquasecurity/trivy/pull/2521/commits/e7f75c227823c6ba3f1e42832cedf7e8a31d4bff) approach? We'll finish scan and report errors later, if any.

2022-07-20 20:30 UTC, josedonizetti reviewed
@dmazhar-cogniance I'm really sorry for the delay, was out for a few days due to a problem. I've added a comment. WDYT?

2022-07-21 09:22 UTC, dmazhar-cogniance commented on pkg/k8s/report/report.go
> +func (r Report) GetErrors() []string {
No worries!
Updated the code to have printErrors method and calling it in the beginning of the `Write` method.
Increased the log level to Error also, please let me know is Warn is more suitable.

2022-07-21 18:12 UTC, josedonizetti approved these changes
Thank you!

2022-07-21 18:34 UTC, merged