fix(secret): add newline escaping for asymmetric private key
aquasecurity/trivy pull request #2532
Opened 2022-07-18 05:03 UTC by DmitriyLewen

## Description
Added newline escaping for Asymmetric Private Key.

## Related issues
- Close #2504

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2022-07-26 18:55 UTC, knqyf263 commented
I requested a review from @afdesk

2022-07-27 05:18 UTC, afdesk requested changes

2022-07-27 05:18 UTC, afdesk commented on pkg/fanal/secret/builtin-rules.go
> +		Regex:           MustCompile(`(?i)-----\s*?BEGIN[ A-Z0-9_-]*?PRIVATE KEY( BLOCK)?\s*?-----[\s]*?(?P<secret>[A-Za-z0-9=+/\\\r\n]+)[\s]*?-----\s*?END[ A-Z0-9_-]*? PRIVATE KEY( BLOCK)?\s*?-----`),
can we add tests for this regex?

2022-07-27 05:18 UTC, afdesk commented on pkg/fanal/secret/builtin-rules.go
> +		Regex:           MustCompile(`(?i)-----\s*?BEGIN[ A-Z0-9_-]*?PRIVATE KEY( BLOCK)?\s*?-----[\s]*?(?P<secret>[A-Za-z0-9=+/\\\r\n]+)[\s]*?-----\s*?END[ A-Z0-9_-]*? PRIVATE KEY( BLOCK)?\s*?-----`),
or did i miss something?

2022-07-27 10:40 UTC, DmitriyLewen commented on pkg/fanal/secret/builtin-rules.go
> +		Regex:           MustCompile(`(?i)-----\s*?BEGIN[ A-Z0-9_-]*?PRIVATE KEY( BLOCK)?\s*?-----[\s]*?(?P<secret>[A-Za-z0-9=+/\\\r\n]+)[\s]*?-----\s*?END[ A-Z0-9_-]*? PRIVATE KEY( BLOCK)?\s*?-----`),
thanks! 
I added tests.

2022-07-28 07:46 UTC, afdesk approved these changes
as for me, a lot of `*` looks not well, I'd prefer five stars
imho

2022-07-28 08:03 UTC, knqyf263 commented
We started with `*****` for long secrets, but @liamg changed it in https://github.com/aquasecurity/trivy/pull/2410. I guess he needed the same length as the original secret for this kind of output.
![image](https://user-images.githubusercontent.com/2253692/181454041-dbb563f3-b6f2-459a-991e-58d9bc648369.png)

2022-07-31 07:18 UTC, knqyf263 approved these changes

2022-07-31 07:18 UTC, merged