adding show-and-tell template to GH discussions
aquasecurity/trivy pull request #3391
Opened 2023-01-05 13:38 UTC by AnaisUrlichs

## Description

adding show-and-tell template to GH discussions

Note: I am not sure if this is working as expected

2023-01-05 13:41 UTC, itaysk commented on .github/DISCUSSION_TEMPLATE/show-and-tell.yml
> +title: "[Show and tell] "
This means the title of the newly created discussion has this prefix?

2023-01-05 14:04 UTC, itaysk requested changes

2023-01-05 14:04 UTC, itaysk commented on .github/DISCUSSION_TEMPLATE/show-and-tell.yml
> +title: "[Show and tell] "
(see my other comment about company name for why this suggestion)

2023-01-16 17:47 UTC, AnaisUrlichs commented on .github/DISCUSSION_TEMPLATE/show-and-tell.yml
> +    id: company
People will not know that they should put as title the company -- so I would rather ask explicitly. 
In the discussion YAML itself on the first line, the title has to be "Show and tell" so the form shows up when people select show and tell

2023-01-16 17:49 UTC, AnaisUrlichs commented on .github/DISCUSSION_TEMPLATE/show-and-tell.yml
> +title: "[Show and tell] "
In the GH documentation on creating a discussion form they explicitly said that the title of the YAML for the form has to match the selection name in the GH discussions of your project -- I think this does not mean that people cannot set a title for their discussion (?)

2023-01-16 17:50 UTC, AnaisUrlichs commented on .github/DISCUSSION_TEMPLATE/show-and-tell.yml
> +      required: true
hmm you have a point

2023-01-16 18:03 UTC, itaysk commented on .github/DISCUSSION_TEMPLATE/show-and-tell.yml
> +title: "[Show and tell] "
I think you might have confused name of file with name of form?

> You can create custom discussion category forms by adding a YAML form definition file ... The name must correspond with the slug for one of your discussion categories. For example, the template for the "Announcements" category should be .github/DISCUSSION_TEMPLATE/announcements.yml.

2023-01-17 08:04 UTC, AnaisUrlichs commented on .github/DISCUSSION_TEMPLATE/show-and-tell.yml
> +      render: bash
Would you like the type to be markdown?

2023-01-17 08:24 UTC, itaysk commented on .github/DISCUSSION_TEMPLATE/show-and-tell.yml
> +      render: bash
That's also not desired (will render as markdown codeblock). Just remove it

2023-01-17 08:36 UTC, itaysk approved these changes

2023-01-17 08:38 UTC, itaysk commented
@knqyf263 you're required as code owner

2023-01-17 08:40 UTC, knqyf263 commented
Did we test this template?

2023-01-17 09:09 UTC, AnaisUrlichs commented
@knqyf263 it does not really fall under this any of those types tho :D will call it "docs"

2023-01-17 12:34 UTC, knqyf263 commented
@itaysk @AnaisUrlichs Did either of you two confirm the template actually work in fork or another repository?

2023-01-18 11:39 UTC, AnaisUrlichs commented
@knqyf263 will do

2023-01-18 12:22 UTC, itaysk commented
@AnaisUrlichs can you also please also add an optional field to provide a link to logo? maybe in the future we can create a page like this in the Trivy website: https://fluxcd.io/adopters/

2023-01-22 14:38 UTC, AnaisUrlichs commented
@knqyf263 @itaysk I made some changes and checked that the template works on my branch -- please let me know if you would like anything else to be changed
<img width="610" alt="Screenshot 2023-01-22 at 14 34 39" src="https://user-images.githubusercontent.com/33576047/213921523-8d1095cf-df51-4c17-842f-aa1779c6e812.png">

2023-01-22 15:33 UTC, knqyf263 approved these changes
Looks great to me!

2023-01-22 15:34 UTC, merged