feat(misconf): show the resource name in the report
aquasecurity/trivy pull request #4806
Opened 2023-07-11 08:27 UTC by nikpivkin

## Description

## Related issues
- Close https://github.com/aquasecurity/trivy/issues/4581

## Related PRs
- [ ] https://github.com/aquasecurity/defsec/pull/1383

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2023-07-25 00:07 UTC, simar7 commented
any update on this @nikpivkin?

2023-07-25 03:23 UTC, nikpivkin commented
@simar7 The changes made to defsec have not yet been merged into trivy

2023-08-02 23:35 UTC, simar7 requested changes
We can add a small test for this change as described. In addition lets also document this behavior as it a user facing change.

2023-08-02 23:35 UTC, simar7 commented on pkg/report/table/misconfig.go
> +
Can we add a test case for this? You can add it here https://github.com/aquasecurity/trivy/blob/6cc3c4c9e59d6dcfd4d00ef88c6a25e834bf292d/pkg/report/table/misconfig_test.go

2023-08-04 19:26 UTC, simar7 approved these changes

2023-08-04 19:27 UTC, simar7 commented
hi @knqyf263 this is a new feature and should go into v0.45.0, is there way to have a merge queue by milestone? Otherwise we will have to wait to merge until the end of the month is here.

2023-08-04 19:36 UTC, knqyf263 commented
>hi @knqyf263 this is a new feature and should go into v0.45.0, is there way to have a merge queue by milestone?

As far as I know, there is no way to do that.

> Otherwise we will have to wait to merge until the end of the month is here.

But v0.44.1 will be out next week, and we can merge this PR just after that.

2023-08-10 08:03 UTC, knqyf263 commented
v0.44.1 is out. I'll see if everything is fine in v0.44.1 (if there is a problem, we need to cut v0.44.2) and merge this PR.

2023-08-23 12:23 UTC, merged