feat(cli): add --tf-exclude-downloaded-modules flag
aquasecurity/trivy pull request #4810
Opened 2023-07-12 05:09 UTC by nikpivkin

## Description

## Related issues
- Close https://github.com/aquasecurity/trivy/issues/4618

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2023-07-12 22:25 UTC, simar7 requested changes
it lgtm, but we should test this option in defsec. It should be added as a test here alongside the other options we have: https://github.com/aquasecurity/defsec/blob/master/pkg/scanners/terraform/scanner_test.go

2023-07-13 04:57 UTC, nikpivkin commented
@simar7 I [added](https://github.com/aquasecurity/defsec/pull/1384) a test.

2023-07-13 18:09 UTC, simar7 approved these changes
Nice lgtm!

2023-07-16 08:55 UTC, knqyf263 approved these changes

2023-07-16 09:20 UTC, merged