Update README.md
aquasecurity/trivy pull request #727
Opened 2020-10-27 12:32 UTC by rishabh710

Addition of contributing

2020-10-27 12:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/trivy?pullRequest=727) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/trivy?pullRequest=727) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/trivy?pullRequest=727) it.</sub>

2020-10-28 21:47 UTC, simar7 requested changes

2020-10-28 21:47 UTC, simar7 commented on README.md
> +We also use the GitHub issue tracker to track feature requests. If you have an idea to make kube-bench even more awesome follow the steps below.
```suggestion
We also use the GitHub issue tracker to track feature requests.
```

2020-10-28 21:47 UTC, simar7 commented on README.md
> +- Remember users might be searching for your issue in the future, so please give it a meaningful title to helps others.
```suggestion
```

2020-10-28 21:47 UTC, simar7 commented on README.md
> +- Your PR is more likely to be accepted if it includes tests. (We have not historically been very strict about tests, but we would like to improve this!).
```suggestion
- Your PR is more likely to be accepted if it includes tests. If you're having difficulty with writing tests, please feel free to reach out to one of us and we'll be happy to guide you on to the right path.
```

2020-10-28 21:47 UTC, simar7 commented on README.md
> +- Happy coding!
```suggestion
```

2020-10-28 21:47 UTC, simar7 commented
Please sign the CLA.

2020-10-29 04:54 UTC, knqyf263 commented
We already have [CONTRIBUTING.md](https://github.com/aquasecurity/trivy/blob/master/CONTRIBUTING.md)

2020-10-29 04:57 UTC, simar7 commented
I didn't even notice that. This PR should be closed in that case.

2020-10-29 04:57 UTC, closed without merging