Added nodeSelector, affinity and tolerations to helm chart
aquasecurity/trivy pull request #803
Opened 2021-01-08 09:15 UTC by ctolon22

Fixes #800

2021-01-08 09:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/trivy?pullRequest=803) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/trivy?pullRequest=803) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/trivy?pullRequest=803) it.</sub>

2021-01-11 05:23 UTC, czunker requested changes
Thanks @ctolon22 

Please also update the README for the chart and bump the chart version.

2021-01-11 12:03 UTC, czunker approved these changes
lgtm

2021-01-11 14:33 UTC, knqyf263 approved these changes

2021-01-11 14:33 UTC, merged

2021-01-11 14:33 UTC, knqyf263 commented
Thank you so much!