remove SARIF helpUri if empty (#841)
aquasecurity/trivy pull request #845
Opened 2021-02-16 01:29 UTC by ronaudinho

resolves #841

2021-02-16 21:38 UTC, simar7 requested changes
Thanks @ronaudinho for making a PR. We should test this behaviour as part of a unit test. As SARIF format is now getting more and more usage it is critical to test various behaviours via a unit test. 

Currently we don't have a unit test (only integration tests) but we can add one easily as follows:

In `writer_test.go` you can create a new test as follows:
```
func TestReportWriter_SARIFTemplate(t *testing.T) {
	inputTemplate, _ := ioutil.ReadFile("../../contrib/sarif.tpl")

	output := bytes.Buffer{}
	report.WriteResults("template", &output, nil, report.Results{
		{
			Target: "footarget",
			Type:   "footype",
			Vulnerabilities: []types.DetectedVulnerability{
				{
					VulnerabilityID:  "CVE-1234-5678",
					PkgName:          "foopackage",
					InstalledVersion: "1.2.3",
					FixedVersion:     "4.5.6",
					SeveritySource:   "NVD",
					PrimaryURL:       "",
					Vulnerability: dbTypes.Vulnerability{
						Title:       "foovuln",
						Description: "foodesc",
						Severity:    "CRITICAL",
					},
				},
			},
		},
	}, string(inputTemplate), false)

	assert.JSONEq(t, `{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Trivy",
          "informationUri": "https://github.com/aquasecurity/trivy",
          "fullName": "Trivy Vulnerability Scanner",
          "version": "v0.15.0",
          "rules": [
            {
              "id": "[CRITICAL] CVE-1234-5678",
              "name": "dockerfile_scan",
              "shortDescription": {
                "text": "CVE-1234-5678 Package: foopackage"
              },
              "fullDescription": {
                "text": "foovuln."
              },
              "help": {
                "text": "Vulnerability CVE-1234-5678\nSeverity: CRITICAL\nPackage: foopackage\nInstalled Version: 1.2.3\nFixed Version: 4.5.6\nLink: [CVE-1234-5678]()",
                "markdown": "**Vulnerability CVE-1234-5678**\n| Severity | Package | Installed Version | Fixed Version | Link |\n| --- | --- | --- | --- | --- |\n|CRITICAL|foopackage|1.2.3|4.5.6|[CVE-1234-5678]()|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "CRITICAL",
                  "foopackage"
                ],
                "precision": "very-high"
              }
            }]
        }
      },
      "results": [
        {
          "ruleId": "[CRITICAL] CVE-1234-5678",
          "ruleIndex": 0,
          "level": "error",
          "message": {
            "text": "foodesc."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        }],
      "columnKind": "utf16CodeUnits"
    }
  ]
}`, output.String())
}
```

You can then further expand this by making into a table driven test for different behaviours, namely: 1. no `PrimaryURL` 2. with `PrimaryURL`.

2021-02-18 07:26 UTC, ronaudinho commented
added tests for with/without `PrimaryURL`. not sure why goreleaser fails though, do you have any idea why?

2021-02-19 20:23 UTC, simar7 commented
> added tests for with/without `PrimaryURL`. not sure why goreleaser fails though, do you have any idea why?

Looks like it was a transient failure. I re-triggered and it's fine.

2021-02-19 20:23 UTC, simar7 approved these changes
Thanks for the tests! It LGTM!

2021-02-19 20:24 UTC, merged